name: Build and Test
on:
  push:
    branches:
      - 'main'
jobs:
  setup:
    name: Yarn install & cache
    runs-on: buildjet-4vcpu-ubuntu-2204
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dangerous-git-checkout
      - uses: ./.github/actions/yarn-install
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
      - name: Test and coverage
        run: yarn test
      - name: Check coverage output
        run: cat coverage/lcov.info
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  