name: Build and Test

on:
  push:
    branches:
      - 'main'

jobs:
  ... # Run other jobs you want here

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
      - name: Install dependencies
        run: yarn install
      - name: Test and coverage
        run: yarn test
      - name: Check coverage output
        run: cat coverage/lcov.info
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  