name: Yarn install

on:
 push:
   branches:
     - main
 pull_request:
   types: [opened, synchronize, reopened]

jobs:
  setup:
    name: Yarn install & cache
    runs-on: buildjet-4vcpu-ubuntu-2204
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dangerous-git-checkout
      - uses: ./.github/actions/yarn-install
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@<action version@v2.3.0 
      env:
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

  